name: Update Port Entity with PR Count

on:
  workflow_dispatch:

jobs:
  update-port-entity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq

      - name: Get PR Count
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          PR_COUNT=$(gh pr list --state open --json number | jq '.[] | length')
          echo "PR Count: $pr_count"
          echo "PR_COUNT=$PR_COUNT" >> $GITHUB_ENV
          echo "::set-output name=pr_count::$pr_count"

      - name: Use PR Count
        run: |
          echo "Number of open PRs: $PR_COUNT"

      - name: Update Port Entity
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          identifier: Service
          title: Service
          blueprint: framework
          properties: |
            {
              "open_pr_count": "${{ steps.get-pr-count.outputs.pr_count }}"
            }
       