name: Update Port Entity with JWT Token

on:
  push:
    branches: ['main']

jobs:
  update_port_entity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          identifier: Service
          title: Service
          blueprint: Integer
          properties: ' {
              "content": "New Framework",
              "description": "This framework supports modern applications.",
              "state": "active",
            }'
          relations: '{}'